### ISSUE TITLE
[Bug] list index problem in get_my_timetable()

### ISSUE THREAD

**Issue by rine77** [EdupageAPI/edupage-api#81]
**Describe the bug**
I cant use get_my_timetable() from your example. 
In my case I think there comes only one element but in your code you use [1]...

**Your code**
```python
import datetime

from edupage_api import Edupage

edupage = Edupage()
edupage.login_auto("bla@blubb", "pass")

# My timetable
date = datetime.date(2024, 11, 1)
timetable = edupage.get_my_timetable(date)

```

**Error message**
```
Traceback (most recent call last):
  File "/home/rine/Projekte/homeassistantedupage/custom_components/homeassistantedupage/test/test.py", line 10, in <module>
    timetable = edupage.get_my_timetable(date)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rine/Projekte/homeassistantedupage/.venv/lib/python3.12/site-packages/edupage_api/__init__.py", line 164, in get_my_timetable
    return Timetables(self).get_my_timetable(date)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rine/Projekte/homeassistantedupage/.venv/lib/python3.12/site-packages/edupage_api/module.py", line 100, in __impl
    return method(self, *method_args, **method_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rine/Projekte/homeassistantedupage/.venv/lib/python3.12/site-packages/edupage_api/timetables.py", line 282, in get_my_timetable
    plan = self.__get_date_plan(date)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rine/Projekte/homeassistantedupage/.venv/lib/python3.12/site-packages/edupage_api/timetables.py", line 180, in __get_date_plan
    curriculum_json = curriculum_response.text.split(response_start)[1].rsplit(
                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
```

**Expected behavior**
It should deliver the timetable for the selected date (2024/11/10)

**Version**
- Edupage API version: **0.11.0**
- Python version: **3.12**

**Comment by ivanhrabcak** [comment]
Can you send me a message on discord (ivicek)? It would be best if we could debug this issue together.
